---
{{- if .Values.weather.apiKey -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "weather-au-exporter.fullname" . }}
  labels:
    app: {{ template "weather-au-exporter.name" . }}
    chart: {{ template "weather-au-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  OWM_API_KEY: {{ .Values.weather.apiKey | b64enc | quote }}
{{- end }}
{{ if .Values.weather.sealedApiKey -}}
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ template "weather-au-exporter.fullname" . }}
  labels:
    app: {{ template "weather-au-exporter.name" . }}
    chart: {{ template "weather-au-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  encryptedData:
    OWM_API_KEY: {{ .Values.weather.sealedApiKey | quote }}
  template:
    metadata:
      name: {{ template "weather-au-exporter.fullname" . }}
      namespace: {{ .Release.Namespace }}
      labels:
        app: {{ template "weather-au-exporter.name" . }}
        chart: {{ template "weather-au-exporter.chart" . }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
{{- end }}
