{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "weather-au-exporter.fullname" . }}
  labels:
    app: {{ template "weather-au-exporter.name" . }}
    chart: {{ template "weather-au-exporter.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetport }}
      protocol: TCP
      name: http
  selector:
    app: {{ template "weather-au-exporter.name" . }}
    release: {{ .Release.Name }}
{{- end }}
